version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - db-volume:/var/lib/mysql

  migration:
    image: flyway/flyway
    depends_on:
      - db
    volumes:
      - ./database/schema:/flyway/sql
  
  backend:
    build:
      context: ./backend
    working_dir: /app
    command: reflex -r '\.go$$' -s -- sh -c 'go run main.go'
    environment:
      - DATABASE_DATASOURCE=${DATABASE_DATASOURCE}
    ports:
      - 1323:1323
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    working_dir: /app
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - frontend-node_modules:/app/node_modules
    tty: true # Alive daemon

volumes:
  db-volume:
  frontend-node_modules: